name: CodeReady
options:
  bundleIdPrefix: com.jank
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  CodeReady:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CodeReady
        excludes:
          - README.md
    resources:
      - path: CodeReady/Data
      - path: CodeReady/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jank.codeready
        PRODUCT_NAME: "LEO Study"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_CFBundleDisplayName: "LEO Study"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        TARGETED_DEVICE_FAMILY: 1
    scheme:
      testTargets: []
