import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import './KnowledgeInsights.css'

type Code = {key:string;codeSet:'penal'|'hs'|'vehicle';sectionNumber:string;title:string;correct:number;incorrect:number;attempts:number;accuracy:number|null;streak:number;evidence:string;status:string}
type Insight = {generatedAt:string;totalCodes:number;testedCodes:number;untestedCodes:number;coverage:number;attempts:number;accuracy:number|null;mastered:number;earlySignals:number;subjects:{codeSet:Code['codeSet'];label:string;totalCodes:number;testedCodes:number;coverage:number;attempts:number;accuracy:number|null;mastered:number;needsFocus:number}[];priorities:Code[];strengths:Code[];codes:Code[];methodology:string;coachAvailable:boolean}
type Reply = {summary:string;steps:{title:string;detail:string;codeKey:string|null}[];caveat:string;usage?:{remaining:number;limit:number};cached:boolean}
async function request(path:string, body?:unknown, signal?:AbortSignal) {
 const {data}=await supabase!.auth.getSession()
 if(!data.session)throw Error('Sign in to see your insights.')
 const r=await fetch(`/api/membership/${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${data.session.access_token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal})
 const json=await r.json();if(!r.ok)throw Error(json.error||'Please try again.');return json
}
export function KnowledgeInsights({onStudy}:{onStudy:(codeSet:Code['codeSet'],sectionNumber:string)=>void}) {
 const [data,setData]=useState<Insight|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0)
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[expanded,setExpanded]=useState(false)
 useEffect(()=>{const controller=new AbortController();request('knowledge',undefined,controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[refresh])
 const rows=useMemo(()=>data?.codes.filter(c=>(filter==='all'||c.status===filter)&&`${c.sectionNumber} ${c.title}`.toLowerCase().includes(query.toLowerCase()))||[],[data,filter,query])
 if(!data)return <section className="knowledge-panel"><h2>Your knowledge map</h2>{error?<><p role="alert">{error}</p><button className="secondary" onClick={()=>{setError('');setRefresh(x=>x+1)}}>Try again</button></>:<p role="status">Gathering your practice evidence…</p>}</section>
 return <section className="knowledge-insights" aria-labelledby="knowledge-title">
  <header className="knowledge-heading"><div><p className="eyebrow">Your knowledge, in focus</p><h2 id="knowledge-title">Know what’s solid.<br/>See what’s next.</h2><p>A clear picture of your recorded practice, with room for what you haven’t explored yet.</p></div><button className="secondary" onClick={()=>{setError('');setRefresh(x=>x+1)}}>Refresh insights</button></header>
  {error?<p role="alert">{error}</p>:null}
  <div className="knowledge-metrics">{[['Practice accuracy',data.accuracy===null?'—':`${data.accuracy}%`,`${data.attempts} recorded answers`],['Library coverage',`${data.coverage}%`,`${data.testedCodes} of ${data.totalCodes} codes practiced`],['Not yet tested',String(data.untestedCodes),'An opportunity to broaden your practice'],['Mastered codes',String(data.mastered),'20 consecutive correct answers']].map(([label,value,detail])=><article key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
  <div className="knowledge-subjects">{data.subjects.map(s=><article className="knowledge-panel" key={s.codeSet}><h3>{s.label}</h3><div className="knowledge-subject-value"><strong>{s.accuracy===null?'—':`${s.accuracy}%`}</strong><span>accuracy · {s.attempts} answers</span></div><div className="knowledge-meter" role="meter" aria-label={`${s.label} coverage`} aria-valuenow={s.coverage} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${s.coverage}%`}}/></div><p>{s.testedCodes} of {s.totalCodes} codes explored</p><small>{s.mastered} mastered · {s.needsFocus} need focus</small></article>)}</div>
  <div className="knowledge-focus-grid"><article className="knowledge-panel"><p className="eyebrow">Make your next session count</p><h3>Your next review</h3>{data.priorities.length?data.priorities.slice(0,3).map(c=><button key={c.key} className="knowledge-code" onClick={()=>onStudy(c.codeSet,c.sectionNumber)}><span><strong>{c.sectionNumber} · {c.title}</strong><small>{c.accuracy}% across {c.attempts} answers · {c.evidence}</small></span><span aria-hidden="true">→</span></button>):<p>{data.attempts?'Your practiced codes are mastered. Try something new or revisit earlier material.':'Start a short flashcard session to establish your first practice signals.'}</p>}</article><article className="knowledge-panel"><p className="eyebrow">Built through repetition</p><h3>Your strongest signals</h3>{data.strengths.length?data.strengths.slice(0,3).map(c=><button key={c.key} className="knowledge-code" onClick={()=>onStudy(c.codeSet,c.sectionNumber)}><span><strong>{c.sectionNumber} · {c.title}</strong><small>{c.accuracy}% across {c.attempts} answers · {c.streak} correct in a row</small></span><span aria-hidden="true">→</span></button>):<p>After at least five answers on a code, strong results will appear here. A single correct answer is a starting point.</p>}</article></div>
  <StudyCoach insights={data} onStudy={onStudy}/>
  <section className="knowledge-panel knowledge-library"><header><div><p className="eyebrow">Every code, one clear view</p><h3>Explore your knowledge</h3></div><span>{rows.length} codes</span></header><div className="knowledge-controls"><label>Find a code<input value={query} onChange={e=>{setQuery(e.target.value);setExpanded(false)}} placeholder="Search number or topic"/></label><label><span id="knowledge-status-label">Practice status</span><select aria-labelledby="knowledge-status-label" value={filter} onChange={e=>{setFilter(e.target.value);setExpanded(false)}}><option value="all">All codes</option><option value="focus">Needs focus</option><option value="untested">Not yet tested</option><option value="early">Early signals</option><option value="developing">Developing</option><option value="mastered">Mastered</option></select></label></div>
  <div className="knowledge-table-wrap"><table><thead><tr><th>Code / topic</th><th>Accuracy</th><th>Answers</th><th>Evidence</th><th><span className="sr-only">Study</span></th></tr></thead><tbody>{rows.slice(0,expanded?rows.length:12).map(c=><tr key={c.key}><td><strong>{c.sectionNumber}</strong><small>{c.title}</small></td><td>{c.accuracy===null?'—':`${c.accuracy}%`}</td><td>{c.attempts}</td><td>{c.evidence}</td><td><button className="secondary" aria-label={`Review ${c.sectionNumber}`} onClick={()=>onStudy(c.codeSet,c.sectionNumber)}>Review</button></td></tr>)}</tbody></table></div>{!rows.length?<p>No codes match these filters.</p>:null}{rows.length>12?<button className="secondary" onClick={()=>setExpanded(x=>!x)}>{expanded?'Show fewer codes':`Show all ${rows.length} codes`}</button>:null}</section>
  <details className="knowledge-method"><summary>How to read these insights</summary><p>{data.methodology}</p><p>Counts come from your recorded code practice. The weekly activity and game history below may cover different activities; they are not interchangeable measures.</p><small>Updated {new Date(data.generatedAt).toLocaleString()}</small></details>
 </section>
}
function StudyCoach({insights,onStudy}:{insights:Insight;onStudy:(codeSet:Code['codeSet'],sectionNumber:string)=>void}) {
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[question,setQuestion]=useState(''),[reply,setReply]=useState<Reply|null>(null),[history,setHistory]=useState<{role:string;text:string}[]>([])
 const [mode,setMode]=useState('overview')
 async function ask(nextMode:string){if(busy)return;setBusy(true);setError('');setMode(nextMode);try{const answer=await request('coach',{mode:nextMode,question:nextMode==='ask'?question:'',history});setReply(answer);setHistory(old=>[...old,{role:'user',text:nextMode==='ask'?question:nextMode},{role:'assistant',text:answer.summary}].slice(-4));setQuestion('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="knowledge-panel study-coach" aria-labelledby="study-coach-title"><header><div><p className="eyebrow">A second perspective, when you want it</p><h3 id="study-coach-title">Your AI study coach</h3><p>Turn your practice evidence into an achievable next step.</p></div><button className="secondary" aria-expanded={open} onClick={()=>setOpen(x=>!x)}>{open?'Hide coach':'Open study coach'}</button></header>{open?<div className="study-coach-body"><p className="coach-privacy">When you ask, your practice summary and this conversation are sent to OpenAI. Your name, email, class chat and direct messages are not included. AI suggestions can be mistaken; use your course material to verify content.</p>{!insights.coachAvailable?<p className="coach-notice" role="status">The AI connection is being set up. Your knowledge map and review tools are ready to use now.</p>:<><div className="coach-prompts">{[['overview','Explain my results'],['weaknesses','Find my gaps'],['plan','Plan 15 minutes'],['habits','Improve my routine']].map(([id,label])=><button className="secondary" key={id} disabled={busy} aria-pressed={Boolean(reply)&&mode===id} onClick={()=>void ask(id)}>{label}</button>)}</div>{busy?<p role="status">Your coach is reviewing the practice evidence…</p>:null}{error?<p role="alert">{error}</p>:null}{reply?<article className="coach-response" aria-live="polite"><p>{reply.summary}</p><ol>{reply.steps.map((step,i)=>{const code=insights.codes.find(c=>c.key===step.codeKey);return <li key={i}><strong>{step.title}</strong><p>{step.detail}</p>{code?<button className="secondary" onClick={()=>onStudy(code.codeSet,code.sectionNumber)}>Review {code.sectionNumber} →</button>:null}</li>})}</ol><small>{reply.caveat}</small>{reply.usage?<p className="coach-allowance">{reply.usage.remaining} of {reply.usage.limit} requests left today · resets at midnight UTC</p>:null}</article>:null}<form onSubmit={e=>{e.preventDefault();void ask('ask')}}><label htmlFor="coach-question">Ask about your study progress</label><textarea id="coach-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000} placeholder="What should I focus on before my next practice test?" rows={2}/><div><small>{question.length}/1,000</small><button className="primary" disabled={busy||!question.trim()}>Ask your coach</button></div></form>{history.length?<button className="secondary" disabled={busy} onClick={()=>{setReply(null);setHistory([]);setError('')}}>Clear conversation</button>:null}</>}</div>:null}</section>
}
