import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { sanitizeProStudyPreferences, type ProAnalytics, type ProStudyPreferences, type PracticeSetup } from '../lib/proStudy'
import './ProStudyTools.css'
type Props = { preferences?: ProStudyPreferences; onPreferences:(value:ProStudyPreferences)=>void; onPractice:(setup:PracticeSetup)=>void; onDrill:(codeSet:'penal'|'hs'|'vehicle',section:string)=>void }
export function ProStudyTools(props:Props) {
  const [analytics,setAnalytics]=useState<ProAnalytics|null>(null)
  const [error,setError]=useState(''), [retry,setRetry]=useState(0)
  const [saving,setSaving]=useState(false),[saveStatus,setSaveStatus]=useState('')
  const [name,setName]=useState(''), [module,setModule]=useState<PracticeSetup['module']>('tmas1'), [length,setLength]=useState(20)
  const preferences=sanitizeProStudyPreferences(props.preferences)
  useEffect(()=>{let cancelled=false;const load=async()=>{try{const session=await supabase?.auth.getSession();const response=await fetch('/api/membership/analytics',{headers:{Authorization:`Bearer ${session?.data.session?.access_token || ''}`}});const data=await response.json();if(!response.ok)throw Error(data.error||'Your report could not be loaded');if(!cancelled){setAnalytics(data);setError('')}}catch(error){if(!cancelled)setError(error instanceof Error?error.message:'Your report could not be loaded')}};void load();return()=>{cancelled=true}},[retry])
  const exportReport=()=>{if(!analytics)return;const cell=(value:unknown)=>`"${String(value).replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;const rows=[['180 Academy Pro progress report',analytics.generatedAt],['Week starting (UTC)',analytics.weekStart],['Sessions this week',analytics.current.sessions],['Sessions last week',analytics.previous.sessions],['Average session accuracy this week',analytics.current.accuracy??'No data'],['Average session accuracy last week',analytics.previous.accuracy??'No data'],[],['Subject','Code','Title','Attempts','Accuracy'],...analytics.weaknesses.map(row=>[row.codeSet,row.sectionNumber,row.title,row.attempts,row.accuracy])];const url=URL.createObjectURL(new Blob([rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`180-academy-progress-${analytics.weekStart}.csv`;link.click();URL.revokeObjectURL(url)}
  const savePreferences=async(value:ProStudyPreferences)=>{if(saving)return;setSaving(true);setSaveStatus('');try{if(!supabase)throw Error('Sign in again to save your practice settings.');const result=await supabase.rpc('save_academy_pro_preferences',{p_preferences:value});if(result.error)throw result.error;props.onPreferences(value);setSaveStatus('Study settings saved')}catch{setSaveStatus('We could not save your settings. Please try again.')}finally{setSaving(false)}}
  const saveSetup=()=>{const setup:PracticeSetup={id:crypto.randomUUID(),name:name.trim()||`${module.toUpperCase()} · ${length} questions`,module,length};void savePreferences({...preferences,setups:[setup,...preferences.setups].slice(0,8)});setName('')}
  return <section className="pro-tools" aria-labelledby="pro-tools-title"><header><div><p className="eyebrow">ACADEMY PRO · YOUR STUDY TOOLKIT</p><h2 id="pro-tools-title">Turn insight into action</h2><p>Your personal plan, focused practice, and progress in one place.</p></div><button className="secondary" disabled={!analytics} onClick={exportReport}>Download progress report</button></header>
    {error?<p role="alert">{error} <button className="secondary" onClick={()=>setRetry(value=>value+1)}>Try again</button></p>:!analytics?<p role="status">Preparing your study report…</p>:null}
    {analytics?<><div className="pro-comparisons"><article><small>Sessions this week</small><strong>{analytics.current.sessions}</strong><span>{analytics.sessionDelta>0?'+':''}{analytics.sessionDelta} compared with last week</span></article><article><small>Average session accuracy</small><strong>{analytics.current.accuracy===null?'—':`${analytics.current.accuracy}%`}</strong><span>{analytics.accuracyDelta===null?'Complete sessions in both weeks to compare':`${analytics.accuracyDelta>0?'+':''}${analytics.accuracyDelta} percentage points`}</span></article><article><small>Your weekly goal</small><strong>{analytics.current.sessions} / {preferences.weeklySessions}</strong><label>Target sessions<select value={preferences.weeklySessions} onChange={event=>void savePreferences({...preferences,weeklySessions:Number(event.target.value)})}>{[3,5,7,10,14].map(value=><option key={value} value={value}>{value} sessions</option>)}</select></label><progress value={Math.min(analytics.current.sessions,preferences.weeklySessions)} max={preferences.weeklySessions} aria-label="Weekly session goal"/></article></div>
      <div className="pro-tools-grid"><article className="card"><h3>Your personal weekly plan</h3><p className="muted">{Math.max(0,preferences.weeklySessions-analytics.current.sessions)} sessions left toward your goal. Start with your lowest-accuracy topics.</p><ol className="pro-plan-list">{analytics.weaknesses.slice(0,3).map((row,index)=><li key={`${row.codeSet}-${row.sectionNumber}`}><span>Focus {index+1}</span><strong>{row.sectionNumber} · {row.title}</strong><small>{row.accuracy}% accuracy across {row.attempts} attempts</small><button className="secondary" onClick={()=>props.onDrill(row.codeSet,row.sectionNumber)}>Start focused drill</button></li>)}</ol>{!analytics.weaknesses.length?<p>Practice a few code sets to build your first personalized plan.</p>:null}<p className="pro-note">Based on your recorded practice. This is study guidance, not an official exam-readiness assessment.</p></article><article className="card"><h3>Your 28-day study calendar</h3><div className="pro-calendar" role="img" aria-label="Completed study sessions over the past 28 days">{analytics.calendar.map(day=><span key={day.date} className={`activity-${Math.min(3,day.count)}`} title={`${day.date}: ${day.count} sessions`}><small>{Number(day.date.slice(-2))}</small></span>)}</div><p className="pro-note">Darker squares mean more completed sessions. Calendar and weekly reports use UTC dates.</p><div className="pro-weaknesses"><h4>Where extra practice can help</h4>{analytics.weaknesses.slice(0,5).map(row=><button key={`${row.codeSet}-${row.sectionNumber}`} onClick={()=>props.onDrill(row.codeSet,row.sectionNumber)}><span>{row.sectionNumber} · {row.title}</span><strong>{row.accuracy}%</strong></button>)}</div></article></div></>:null}
    <article className="card pro-saved-setups"><h3>Saved practice setups</h3><p className="muted">Keep up to eight favorite T-MAS setups ready for your next session.</p><div className="pro-setup-form"><label>Name<input maxLength={40} value={name} onChange={event=>setName(event.target.value)} placeholder="My morning practice"/></label><label>Module<select value={module} onChange={event=>setModule(event.target.value as PracticeSetup['module'])}>{['tmas1','tmas2','tmas3'].map(value=><option key={value} value={value}>{value.toUpperCase()}</option>)}</select></label><label>Questions<select value={length} onChange={event=>setLength(Number(event.target.value))}>{[10,20,50,100].map(value=><option key={value} value={value}>{value}</option>)}</select></label><button className="secondary" disabled={saving} onClick={saveSetup}>{saving?'Saving…':'Save setup'}</button></div><p role="status">{saveStatus}</p><ul>{preferences.setups.map(setup=><li key={setup.id}><div><strong>{setup.name}</strong><small>{setup.module.toUpperCase()} · {setup.length} questions</small></div><button className="primary" disabled={saving} onClick={()=>props.onPractice(setup)}>Start practice</button><button className="secondary" aria-label={`Remove ${setup.name}`} onClick={()=>void savePreferences({...preferences,setups:preferences.setups.filter(row=>row.id!==setup.id)})}>Remove</button></li>)}</ul></article>
  </section>
}
