import { polishPracticeScenarios } from './practiceTestQuestionPolish'
import { resolvePracticeTestTtsRefs } from './practiceTestTtsRefs'
import { tmas3ExpansionScenarios } from './practiceTestTmas3ExpansionScenarios'
import { appendTrueFalseFollowUps } from './practiceTestTrueFalse'

type PracticeTestQuestion = {
  id: string
  ldNumber: string
  ttsRefs: string[]
  objective: string
  prompt: string
  choices: string[]
  correctIndex: number
  explanation: string
  format?: 'multiple_choice' | 'true_false'
}

type PracticeTestScenario = {
  id: string
  title: string
  stem: string
  ldNumbers: string[]
  questions: PracticeTestQuestion[]
}

function tts(refs: string[], summary: string) {
  return `TTS ${refs.join(' / ')} — ${summary}`
}

function question(
  id: string,
  ldNumber: string,
  objective: string,
  prompt: string,
  choices: string[],
  correctIndex: number,
  explanation: string,
): PracticeTestQuestion {
  return {
    id,
    ldNumber,
    ttsRefs: resolvePracticeTestTtsRefs(ldNumber, objective),
    objective,
    prompt,
    choices,
    correctIndex,
    explanation,
  }
}

function scenario(
  id: string,
  title: string,
  stem: string,
  ldNumbers: string[],
  questions: PracticeTestQuestion[],
): PracticeTestScenario {
  return { id, title, stem, ldNumbers, questions }
}

const rawTmas3Scenarios: PracticeTestScenario[] = [
  scenario(
    'tmas3-practice-01',
    'Closed Mall Crew',
    'Officers respond to a closed mall after security sees three people at a jewelry-store roll-up gate. Niko is pulling the gate with a pry tool, Laila is holding a radio and watching the corridor cameras, and Marcos is waiting near an exit with an empty duffel bag. The gate is bent but not open. When detained, Laila says, “We were only going to grab watches if the gate popped.” Marcos later hides the pry tool in a trash can before officers can recover it.',
    ['5'],
    [
      question(
        'tmas3-practice-01-q1',
        '5',
        tts(['5.3C', '5.3D'], 'attempt liability requires intent plus a direct but ineffectual act'),
        'Which fact best supports attempt liability even though the gate never opened?',
        [
          'Niko bent the gate with a pry tool while the group was trying to get inside and steal watches.',
          'The store will probably need a repair estimate before insurance pays the loss.',
          'The mall was closed, so nobody from the public was walking nearby.',
          'The duffel bag was empty when officers first saw Marcos by the exit.',
        ],
        0,
        'Attempt focuses on specific intent and a direct act toward the crime. The pry attempt plus the stated plan supports the attempted offense even without completed entry or taking.',
      ),
      question(
        'tmas3-practice-01-q2',
        '5',
        tts(['5.4B'], 'principals and aiding or encouraging the target crime'),
        'If Laila knowingly watched the cameras so Niko could continue prying the gate, which role is most defensible?',
        [
          'Principal liability as an aider and abettor because her lookout role intentionally assisted the target crime.',
          'Accessory-only liability because she did not personally touch the gate.',
          'No criminal liability because holding a radio is lawful by itself.',
          'Civil liability only because the store suffered no completed theft loss.',
        ],
        0,
        'A person who intentionally aids, promotes, or encourages commission of the target crime can be treated as a principal even without personally doing every act.',
      ),
      question(
        'tmas3-practice-01-q3',
        '5',
        tts(['5.4C'], 'accessory after the fact conduct after the target offense'),
        'Marcos hiding the pry tool after officers arrive most directly raises what additional theory?',
        [
          'Accessory after the fact if he acted after the attempted crime to help someone avoid arrest or prosecution.',
          'Strict liability for any person standing near a closed business.',
          'Conspiracy only if the store owner can prove the tool caused permanent damage.',
          'No issue unless Marcos personally admitted he intended to steal property.',
        ],
        0,
        'Accessory-after-the-fact analysis turns on post-crime assistance meant to help another avoid arrest, trial, conviction, or punishment.',
      ),
      question(
        'tmas3-practice-01-q4',
        '5',
        tts(['5.2B'], 'criminal liability compared with civil remedies'),
        'Which issue is primarily civil rather than the criminal theory officers would submit?',
        [
          'The store owner’s separate claim for reimbursement to fix the bent gate.',
          'Niko’s act of prying the gate with theft intent.',
          'Laila’s lookout conduct during the attempted entry.',
          'Marcos hiding the pry tool after officers arrived.',
        ],
        0,
        'Civil remedies compensate the owner; criminal liability addresses the conduct and mental state that violated penal law.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-02',
    'Trailer VIN Grind',
    'A patrol unit stops a pickup towing a landscaping trailer at 0130 hours because the trailer plate is covered with fresh mud and the safety chains are dragging. The driver says he “borrowed it from a guy at the gas station.” The trailer tongue VIN plate is ground down, several commercial mowers inside have company markings, and dispatch later confirms a matching trailer was stolen from a storage yard two days earlier.',
    ['6'],
    [
      question(
        'tmas3-practice-02-q1',
        '6',
        tts(['6.1A'], 'receiving stolen property and altered identifying information'),
        'Which property-crime conclusion is strongest once officers confirm the trailer was stolen and the driver knew the circumstances were suspicious?',
        [
          'Receiving stolen property, with the altered VIN plate strengthening knowledge and identification issues.',
          'Trespass only, because the driver was on a public roadway when stopped.',
          'Arson, because the VIN damage permanently reduced the trailer’s value.',
          'Civil possession dispute only, because he claimed someone loaned him the trailer.',
        ],
        0,
        'LD 6 tests property crimes by facts, not labels. Possession of recently stolen property plus suspicious explanation and altered identifiers supports receiving-stolen-property analysis.',
      ),
      question(
        'tmas3-practice-02-q2',
        '6',
        tts(['6.1B', '6.1D'], 'property-crime evidence collection and report detail'),
        'Which report detail best preserves the case for filing and property recovery?',
        [
          'The altered VIN area, plate condition, company markings, serial numbers, dispatch confirmation, and the driver’s explanation.',
          'Only the driver’s statement that the trailer was borrowed.',
          'Only the fact that the stop occurred after midnight.',
          'Only the estimated value of the trailer if the owner later wants restitution.',
        ],
        0,
        'A TMAS-style report question wants the facts that prove identity, ownership, knowledge, and recovery. Serial numbers and altered identifiers are not optional details.',
      ),
      question(
        'tmas3-practice-02-q3',
        '6',
        tts(['6.1A'], 'theft-related property crimes and plausible alternative classifications'),
        'Why is “I borrowed it” not enough by itself to end the theft investigation?',
        [
          'Because officers still evaluate possession, knowledge indicators, stolen-property confirmation, and altered identifiers.',
          'Because every borrowed trailer is automatically presumed stolen until proven otherwise.',
          'Because the driver must be arrested for burglary whenever a plate is dirty.',
          'Because ownership disputes can never be handled through criminal investigation.',
        ],
        0,
        'A self-serving explanation does not cancel objective facts. The question tests whether the officer can continue building probable cause from the totality.',
      ),
      question(
        'tmas3-practice-02-q4',
        '6',
        tts(['6.3A', '6.3B'], 'trespass analysis compared with property possession offenses'),
        'If follow-up evidence shows the trailer was taken from a fenced storage yard, what fact would separately matter to a trespass-related theory?',
        [
          'Whether the yard was enclosed or posted and whether entry was unauthorized.',
          'Whether the driver had a valid license when officers stopped him.',
          'Whether the trailer’s tires were properly inflated.',
          'Whether the mower company wanted media coverage of the recovery.',
        ],
        0,
        'Trespass requires facts about unlawful entry or remaining on property; it is a separate analysis from later possession of the stolen trailer.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-03',
    'Bus Loop Robbery',
    'At a transit-center bus loop, a victim says Talia stepped in front of him, grabbed his backpack strap, and said, “Give it up or I’ll cut you.” The victim felt a hard object against his ribs, released the backpack, and fell while pulling away. He has a bruised wrist and later reports dizziness after striking his head on the curb. Officers locate Talia nearby with the backpack and a folded metal comb that resembles a knife handle when closed.',
    ['7'],
    [
      question(
        'tmas3-practice-03-q1',
        '7',
        tts(['7.3A', '7.3B'], 'robbery elements and force or fear'),
        'Which classification best fits the taking of the backpack?',
        [
          'Robbery, because property was taken from the victim’s person or immediate presence by force or fear.',
          'Petty theft only, because the object may not have been an actual knife.',
          'Civil conversion only, because the backpack was recovered soon after.',
          'False imprisonment only, because Talia briefly blocked the walking path.',
        ],
        0,
        'Robbery is driven by the taking from the person or immediate presence by force or fear. The threat and physical confrontation are the key tested facts.',
      ),
      question(
        'tmas3-practice-03-q2',
        '7',
        tts(['7.1A', '7.1B'], 'assault and battery injury analysis'),
        'Which fact best supports documenting a separate battery-related injury issue?',
        [
          'The victim fell during the struggle and had a bruised wrist with possible head-impact symptoms.',
          'Talia still had the backpack when officers found her.',
          'The transit center was busy and several buses were delayed.',
          'The comb looked like a knife handle when folded.',
        ],
        0,
        'LD 7 requires officers to recognize and document unlawful force and injury, not just the property taking.',
      ),
      question(
        'tmas3-practice-03-q3',
        '7',
        tts(['7.1A', '7.3A'], 'threat display and victim fear in person crimes'),
        'How should officers treat the folded comb fact when evaluating force or fear?',
        [
          'It matters because the victim’s reasonable fear can be supported even if the object is later found not to be an actual knife.',
          'It defeats robbery because the displayed object must be a real knife in every case.',
          'It converts the crime into theft only because no blade was opened.',
          'It makes the victim’s statement irrelevant unless video shows the exact object shape.',
        ],
        0,
        'The issue is whether force or fear was used to accomplish the taking. A realistic-looking object can explain the victim’s fear even if later inspection changes weapon classification.',
      ),
      question(
        'tmas3-practice-03-q4',
        '7',
        tts(['7.5A', '7.5B', '7.5C'], 'death-investigation awareness and scene preservation'),
        'If the victim later collapses from a suspected head injury, what is the most defensible follow-up?',
        [
          'Treat the incident as potentially involving a serious injury or death investigation and preserve statements, scene facts, and medical timelines.',
          'Close the robbery report because the backpack was recovered.',
          'Delete injury observations unless the victim dies at the original scene.',
          'Document only the theft value because medical issues belong entirely to fire personnel.',
        ],
        0,
        'TMAS questions often test escalation. A later serious medical outcome makes early injury facts, witness timelines, and scene preservation critical.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-04',
    'Transit Plaza Refusal',
    'During a downtown event, officers see Evan yelling sexual comments at pedestrians, blocking a crosswalk with a portable speaker, and filming under a seated person’s skirt as people wait for a shuttle. When officers contact him, Evan repeatedly steps into traffic and refuses several clear commands to move to the sidewalk. He smells strongly of alcohol, has watery eyes, and cannot explain where he is staying.',
    ['8'],
    [
      question(
        'tmas3-practice-04-q1',
        '8',
        tts(['8.1A', '8.1B'], 'public-order and sexual misconduct statutes'),
        'Which issue should officers evaluate from the under-skirt filming allegation?',
        [
          'A general criminal statute involving invasion-of-privacy or related sexual misconduct facts.',
          'Robbery because the victim’s privacy was taken by force.',
          'Trespass because the filming happened in a public plaza.',
          'Receiving stolen property because the video is stored on a phone.',
        ],
        0,
        'LD 8 includes general criminal statutes that can be missed if the officer treats the event as only a nuisance call.',
      ),
      question(
        'tmas3-practice-04-q2',
        '8',
        tts(['8.2A', '8.2B'], 'obstruction and lawful order analysis'),
        'Which fact most directly supports an obstruction or delay analysis?',
        [
          'Evan repeatedly stepped into traffic and refused clear lawful commands to move to the sidewalk.',
          'The portable speaker was loud enough for people across the plaza to hear.',
          'The event caused traffic congestion before officers arrived.',
          'Several pedestrians disliked Evan’s comments.',
        ],
        0,
        'The tested point is interference with lawful officer duties or refusal to comply with lawful orders, not merely being unpopular or loud.',
      ),
      question(
        'tmas3-practice-04-q3',
        '8',
        tts(['8.1A', '8.1B'], 'public intoxication facts compared with rude conduct'),
        'Which fact set most strongly supports evaluating public intoxication rather than only disturbing behavior?',
        [
          'Alcohol symptoms, inability to care for his safety, and repeatedly stepping into traffic.',
          'Using a portable speaker during a public event.',
          'Making comments that several pedestrians found offensive.',
          'Filming with a phone while standing in a public plaza.',
        ],
        0,
        'Public intoxication analysis requires more than alcohol use; officers articulate impairment plus inability to care for safety or obstruction of public ways.',
      ),
      question(
        'tmas3-practice-04-q4',
        '8',
        tts(['8.1B', '8.2B'], 'classification and report articulation for general criminal statutes'),
        'Which report approach best fits this mixed-call scenario?',
        [
          'Separate each possible statute by facts: filming allegation, obstruction/refusal, intoxication indicators, and witness observations.',
          'Choose only the loudest behavior and ignore the rest to keep the report short.',
          'Use one generic “disturbance” label because public-place crimes are rarely charged.',
          'Document only the officer commands and omit victim or witness statements.',
        ],
        0,
        'LD 8 rewards clean classification. Mixed public-order incidents require separating facts by statute so the report does not blur the legal theories.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-05',
    'Locked Bedroom Child',
    'A teacher requests a welfare check after eight-year-old Mateo arrives at school hungry, wearing the same clothes for several days, and with loop-shaped bruises on his legs. At the apartment, officers hear a child crying behind a locked bedroom door. The caregiver says Mateo “lies for attention” and refuses to open the door. Through a gap, officers see spoiled food, no bedding, and fresh bruising. Mateo says quietly that he is punished by being locked inside overnight.',
    ['9'],
    [
      question(
        'tmas3-practice-05-q1',
        '9',
        tts(['9.1A', '9.1B'], 'child abuse and neglect indicators'),
        'Which fact pattern most strongly points to suspected child abuse or neglect?',
        [
          'Loop-shaped bruises, hunger, repeated dirty clothing, locked-room confinement, and lack of bedding.',
          'The caregiver saying Mateo lies for attention.',
          'The teacher asking for a welfare check instead of making an arrest.',
          'The apartment being messy near the front door.',
        ],
        0,
        'LD 9 expects officers to identify physical abuse indicators and neglect conditions from the totality, even when a caregiver minimizes them.',
      ),
      question(
        'tmas3-practice-05-q2',
        '9',
        tts(['9.2A', '9.2B', '9.2C'], 'mandated reporting and child-abuse documentation'),
        'What is the best report and notification approach?',
        [
          'Document observed injuries, statements, living conditions, timelines, and make the required child-abuse reporting notifications.',
          'Wait for the caregiver to admit discipline before documenting injuries.',
          'Document only the teacher’s concern because officers did not see the punishment occur.',
          'Handle it as a school attendance issue unless Mateo asks to leave home.',
        ],
        0,
        'Officers do not need an admission to document suspected abuse. Required reporting and detailed observations are core LD 9 points.',
      ),
      question(
        'tmas3-practice-05-q3',
        '9',
        tts(['9.3A', '9.3B'], 'emergency protection and temporary custody of a child'),
        'If officers reasonably believe Mateo is in immediate danger behind the locked door, which response is most defensible?',
        [
          'Take protective action consistent with emergency child-safety authority and coordinate with child protective services.',
          'Leave and request a follow-up appointment because the caregiver controls the apartment.',
          'Tell Mateo to unlock the door himself so officers avoid entering.',
          'Issue only a warning because the child is technically inside his residence.',
        ],
        0,
        'LD 9 tests emergency child protection. Immediate safety concerns can justify protective action while officers coordinate with the proper child-welfare partners.',
      ),
      question(
        'tmas3-practice-05-q4',
        '9',
        tts(['9.2D'], 'confidentiality and handling sensitive child-abuse information'),
        'Which handling of the case information is most appropriate?',
        [
          'Limit disclosure to those with a legitimate investigative or protective role and follow child-abuse confidentiality rules.',
          'Share Mateo’s statements with neighbors to locate more witnesses.',
          'Post a public bulletin describing the child’s injuries so the caregiver feels pressure.',
          'Give the full report to anyone who asks because the case involves a child.',
        ],
        0,
        'Child-abuse reporting is sensitive. LD 9 includes confidentiality obligations and careful information handling.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-06',
    'Dorm Room Disclosure',
    'A college resident assistant calls police after Sofia, age 19, reports waking up partially unclothed in another student’s dorm room after a party. Sofia remembers saying she felt sick and wanted to sleep. The student tells officers, “She did not say no once we were in my room,” but admits Sofia was vomiting earlier. Sofia has deleted some messages because she is scared other students will blame her. Bedding, clothing, and hallway video may still exist.',
    ['10'],
    [
      question(
        'tmas3-practice-06-q1',
        '10',
        tts(['10.1A', '10.1B'], 'sex-crime elements and consent analysis'),
        'Which issue is most important to the sex-crime classification analysis?',
        [
          'Whether Sofia had the legal capacity to consent and whether the sexual act occurred under circumstances covered by the statute.',
          'Whether Sofia and the student had met before the party.',
          'Whether the dorm room belonged to the suspect or to another student.',
          'Whether Sofia deleted messages before officers arrived.',
        ],
        0,
        'LD 10 focuses on elements and consent/capacity. Prior acquaintance or embarrassment does not resolve the classification question.',
      ),
      question(
        'tmas3-practice-06-q2',
        '10',
        tts(['10.2A', '10.2B', '10.2C'], 'victim-centered response and trauma-informed interview'),
        'Which officer response best fits LD 10 victim-interview principles?',
        [
          'Use a calm, nonjudgmental interview, explain options, avoid blaming language, and preserve Sofia’s control where possible.',
          'Challenge Sofia immediately about deleted messages to test whether she is lying.',
          'Require Sofia to decide at the scene whether she wants prosecution before any report is taken.',
          'Focus only on whether the suspect used physical force because intoxication does not matter.',
        ],
        0,
        'The victim-centered approach is not soft; it is how officers improve accuracy, preserve cooperation, and avoid trauma-driven reporting failures.',
      ),
      question(
        'tmas3-practice-06-q3',
        '10',
        tts(['10.3C', '10.3D', '10.3E', '10.3F'], 'sex-crime evidence preservation and documentation'),
        'Which evidence package is most important to preserve early?',
        [
          'Bedding/clothing, possible biological evidence, messages, hallway video, witness timelines, and Sofia’s condition before entering the room.',
          'Only the suspect’s statement because Sofia deleted some messages.',
          'Only the resident assistant’s opinion about whether Sofia seemed credible.',
          'Only the party guest list because physical evidence is rarely relevant in dorm cases.',
        ],
        0,
        'LD 10 tests evidence preservation and complete timelines. Deleted messages may matter, but they do not erase physical, digital, and witness evidence.',
      ),
      question(
        'tmas3-practice-06-q4',
        '10',
        tts(['10.4A', '10.4B'], 'sex-offender registration awareness after qualifying convictions'),
        'Why should officers avoid promising Sofia that registration will or will not apply?',
        [
          'Registration consequences depend on the specific offense and later legal disposition, so officers should document facts and avoid legal promises.',
          'Registration never applies to campus-related sex crimes.',
          'Registration applies automatically to every complaint even before charges are filed.',
          'Registration is decided by the resident assistant at the college.',
        ],
        0,
        'Officers need awareness of registration concepts without overstating legal outcomes at the investigative stage.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-07',
    'Mall Juvenile Stop',
    'Mall security detains 15-year-old Jalen after seeing him conceal earbuds and walk past the registers. Officers arrive and learn Jalen is a runaway entry in the system. He has a folding knife clipped inside his waistband, gives his older cousin’s name first, then admits his real name. His mother cannot be reached. Jalen asks whether he is “going to juvie tonight” and says he does not want to talk if it means his probation officer will find out.',
    ['11'],
    [
      question(
        'tmas3-practice-07-q1',
        '11',
        tts(['11.1A', '11.1B', '11.1C'], 'juvenile status, delinquency, and rights'),
        'Which LD 11 classification issue is most important at the start?',
        [
          'Separating Jalen’s alleged theft, runaway status, identity issue, and weapon possession instead of treating all juvenile conduct the same.',
          'Calling every juvenile contact a status offense because Jalen is under 18.',
          'Ignoring the theft because mall security contacted him before officers did.',
          'Treating the cousin’s name as harmless because juveniles cannot commit false-identification offenses.',
        ],
        0,
        'Juvenile law requires correct classification. A juvenile can present delinquency, status, custody, and protective issues in one contact.',
      ),
      question(
        'tmas3-practice-07-q2',
        '11',
        tts(['11.2A', '11.2B', '11.2C', '11.2D', '11.2E'], 'temporary custody and juvenile disposition decisions'),
        'Which next step best fits temporary-custody decision-making?',
        [
          'Evaluate legal grounds for temporary custody, safety, parent/guardian notification efforts, release options, and required documentation.',
          'Release Jalen immediately because shoplifting is nonviolent.',
          'Book Jalen into adult jail until his mother answers the phone.',
          'Let mall security decide whether he goes to juvenile hall.',
        ],
        0,
        'LD 11 tests whether officers can choose and document a lawful juvenile disposition, not simply default to release or secure custody.',
      ),
      question(
        'tmas3-practice-07-q3',
        '11',
        tts(['11.3A', '11.3B', '11.3C'], 'juvenile confinement and custody protections'),
        'If Jalen must wait at the station while a lawful placement decision is made, what principle controls?',
        [
          'Use only confinement or holding conditions allowed for juveniles and document times, supervision, and separation requirements.',
          'Place him in any adult holding cell because officers have not finished the report.',
          'Leave him unsupervised in the lobby because he is not yet booked.',
          'Allow mall security to hold him in their office overnight.',
        ],
        0,
        'Juvenile confinement rules are tested because temporary custody can quickly become unlawful if time, supervision, or separation rules are ignored.',
      ),
      question(
        'tmas3-practice-07-q4',
        '11',
        tts(['11.4A', '11.4B'], 'contributing-to-delinquency awareness and adult influence'),
        'If the cousin admits he told Jalen to steal the earbuds and gave him the knife, what additional issue should officers evaluate?',
        [
          'Whether the adult contributed to Jalen’s delinquency or otherwise encouraged criminal conduct by a minor.',
          'Whether the cousin can be ignored because only Jalen entered the store.',
          'Whether the mall must file a civil claim before officers can investigate the adult.',
          'Whether Jalen’s runaway status prevents any adult from being charged.',
        ],
        0,
        'LD 11 includes adult conduct that contributes to juvenile delinquency. The adult’s role can become its own issue.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-08',
    'Garage Powder Lab',
    'A neighborhood officer contacts Priya after neighbors report chemical smells from a detached garage. Priya has glassware, pill presses, pseudoephedrine packaging, digital scales, blue pills stamped like prescription medication, and a loaded syringe on a workbench. She says the setup is “only for personal use,” but text messages on a visible tablet show customers asking for delivery times. Officers smell strong solvent fumes and see two children’s bicycles just outside the garage door.',
    ['12'],
    [
      question(
        'tmas3-practice-08-q1',
        '12',
        tts(['12.1A', '12.2A', '12.2B'], 'drug categories, possession, and sales indicators'),
        'Which fact combination most strongly supports a possession-for-sales or manufacturing investigation rather than simple personal use?',
        [
          'Pill presses, scales, packaging, customer delivery messages, and chemical-processing equipment.',
          'Priya’s statement that the pills are only for personal use.',
          'The presence of children’s bicycles outside the garage.',
          'The fact that neighbors smelled something unusual.',
        ],
        0,
        'LD 12 tests whether officers identify controlled-substance crime indicators from the totality, including packaging, equipment, quantity, and sales communications.',
      ),
      question(
        'tmas3-practice-08-q2',
        '12',
        tts(['12.3A', '12.3B', '12.3C'], 'elements of crimes involving controlled substances'),
        'Which legal issue must officers still be able to articulate before filing a controlled-substance crime?',
        [
          'The controlled nature of the substance and facts showing knowledge, possession, manufacturing, or sales conduct.',
          'Only that neighbors disliked the odor coming from the garage.',
          'Only that the tablets looked similar to medication.',
          'Only that Priya was standing near the workbench.',
        ],
        0,
        'Controlled-substance cases require elements. Appearance and proximity matter only when tied to knowledge, possession, control, and lab or sales facts.',
      ),
      question(
        'tmas3-practice-08-q3',
        '12',
        tts(['12.4A', '12.4B', '12.4C'], 'clandestine laboratory and illegal cultivation safety response'),
        'What is the best immediate safety approach when officers smell solvent fumes and see lab equipment?',
        [
          'Back out or control access, avoid disturbing chemicals, isolate the area, and request properly equipped specialized resources.',
          'Open all containers to identify the exact substance before calling anyone.',
          'Move the chemicals outside by hand because children may be nearby.',
          'Allow Priya to dismantle the setup while officers write the report.',
        ],
        0,
        'LD 12 lab questions are safety-heavy. Officers should recognize hazards, isolate, notify, and avoid creating ignition or exposure risks.',
      ),
      question(
        'tmas3-practice-08-q4',
        '12',
        tts(['12.2A', '12.3C'], 'paraphernalia and evidence handling'),
        'How should the loaded syringe be handled in the investigation?',
        [
          'As potential paraphernalia and hazardous evidence requiring safe handling, documentation, and packaging protocols.',
          'As irrelevant because the larger lab equipment is more serious.',
          'As proof by itself that every person in the house is selling drugs.',
          'As medical property that officers cannot photograph or describe.',
        ],
        0,
        'Drug evidence can be both legally significant and physically hazardous. Syringes require careful safety and documentation.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-09',
    'Porch Arrest Question',
    'Officers respond to a neighbor’s video showing Omar punching a delivery driver twenty minutes earlier. The driver has a swollen eye and identifies Omar from across the street. Officers see Omar on his front porch with blood on his knuckles. Omar starts walking inside, saying, “You can’t touch me unless you watched it happen.” Officers stop him on the porch, handcuff him, and ask, “Why did you punch him?” Omar answers, “He kept stepping on my grass.”',
    ['15'],
    [
      question(
        'tmas3-practice-09-q1',
        '15',
        tts(['15.3A', '15.3B', '15.3C'], 'detention based on reasonable suspicion'),
        'Before the handcuffs, what most strongly supports detaining Omar?',
        [
          'Recent video, victim identification, visible injury, and blood on Omar’s knuckles tied to the reported assault.',
          'The neighbor’s dislike of Omar from prior disputes.',
          'Omar standing on his own porch after officers arrived.',
          'The delivery driver being angry and wanting Omar arrested.',
        ],
        0,
        'Reasonable suspicion comes from articulable facts linking Omar to the recent assault, not from neighborhood tension alone.',
      ),
      question(
        'tmas3-practice-09-q2',
        '15',
        tts(['15.4A', '15.4B', '15.4E', '15.4F', '15.4G'], 'probable cause and arrest authority'),
        'What is the strongest arrest analysis if the injury and identification are reliable?',
        [
          'Officers evaluate probable cause from the victim statement, corroborating video, injury, and Omar’s matching condition.',
          'Officers cannot arrest because they did not personally see the punch.',
          'Officers must wait for a warrant in every misdemeanor assault investigation.',
          'Officers can arrest only if Omar confesses before being handcuffed.',
        ],
        0,
        'LD 15 tests probable cause and statutory arrest authority. The officer’s personal observation of the punch is not the only path to arrest.',
      ),
      question(
        'tmas3-practice-09-q3',
        '15',
        tts(['15.5B', '15.5C', '15.5F'], 'Miranda and custodial interrogation'),
        'When officers handcuffed Omar and asked why he punched the driver, what issue is most likely raised?',
        [
          'Custodial interrogation and whether Miranda warnings were required before the incriminating question.',
          'A consensual encounter because Omar was still on his porch.',
          'A routine booking question because the answer explained motive.',
          'No issue because officers already had other evidence.',
        ],
        0,
        'A direct question designed to elicit an incriminating response after custody triggers the Miranda analysis.',
      ),
      question(
        'tmas3-practice-09-q4',
        '15',
        tts(['15.6A', '15.6B', '15.6C', '15.6D'], 'admissions, confessions, and interrogation documentation'),
        'Which documentation choice best preserves the statement issue?',
        [
          'Record custody status, exact question, exact answer, whether Miranda was given, and why the question was asked.',
          'Summarize that Omar was “uncooperative” and omit the exact words.',
          'Include only the victim’s version because Omar’s answer may be challenged.',
          'Write that Miranda never matters if probable cause already existed.',
        ],
        0,
        'TMAS-style Miranda questions reward precise documentation. The admissibility issue is easier to evaluate when the sequence and exact words are clear.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-10',
    'Motel Consent Door',
    'Officers investigate a stolen camera tracked to a motel. The registered guest, Dana, opens the door and says officers can “look around for the camera, but not in my roommate’s locked suitcase.” From the doorway, officers see the camera on a desk next to mail addressed to the theft victim and a clear baggie of suspected methamphetamine. Dana’s roommate arrives, refuses consent, and tries to close the door while officers are still in the threshold.',
    ['16'],
    [
      question(
        'tmas3-practice-10-q1',
        '16',
        tts(['16.3D'], 'consent search scope and common authority'),
        'What is the best consent-search rule under these facts?',
        [
          'Dana’s consent may allow a search of areas she has common authority over, but not the roommate’s locked suitcase if she lacks authority over it.',
          'Dana’s consent automatically authorizes opening every container in the room.',
          'The roommate’s refusal erases anything officers already lawfully observed.',
          'Consent is invalid in motel rooms because they are temporary lodging.',
        ],
        0,
        'LD 16 tests authority and scope. Consent is not a blank check; officers must stay within the consenting person’s actual or apparent authority.',
      ),
      question(
        'tmas3-practice-10-q2',
        '16',
        tts(['16.3A', '16.3B'], 'plain view seizure requirements'),
        'Which item is most defensible under plain-view analysis from the doorway?',
        [
          'The camera visible on the desk if officers are lawfully present and its incriminating nature is immediately apparent from the theft investigation.',
          'The locked suitcase because it might contain more stolen property.',
          'Every drawer in the room because the camera was visible.',
          'The roommate’s phone because he tried to close the door.',
        ],
        0,
        'Plain view depends on lawful presence, lawful access, and immediately apparent incriminating character. It does not create unlimited search authority.',
      ),
      question(
        'tmas3-practice-10-q3',
        '16',
        tts(['16.2A', '16.2B', '16.2D', '16.2E'], 'warrant nexus and securing a scene'),
        'If officers need to search the locked suitcase for additional stolen items, what is the most defensible next step?',
        [
          'Secure the scene as legally allowed and seek a warrant supported by facts tying the suitcase to evidence.',
          'Open it immediately because stolen property was already visible elsewhere.',
          'Ask motel staff to open it because they own the building.',
          'Let Dana open it after the roommate refuses because she wants to help officers.',
        ],
        0,
        'The warrant answer is strongest when consent authority is doubtful and officers can articulate a nexus to the item or place to be searched.',
      ),
      question(
        'tmas3-practice-10-q4',
        '16',
        tts(['16.1B', '16.1C', '16.1E'], 'privacy interests and exclusionary-risk awareness'),
        'Why is the roommate’s locked suitcase legally different from the shared desk area?',
        [
          'It carries a stronger privacy expectation and may be outside Dana’s common authority, creating suppression risk if opened without valid authority.',
          'It is immune from search under every circumstance because it is luggage.',
          'It belongs to the motel because it is inside a rented room.',
          'It can be searched only after the roommate physically attacks officers.',
        ],
        0,
        'LD 16 tests expectation of privacy and scope. Officers must recognize when a container requires a different authority than the room area around it.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-11',
    'Rooftop Knife Crisis',
    'Officers respond to a parking-structure rooftop where Adrian is near the edge holding a knife and yelling that he wants officers to leave. A crowd has gathered below. One officer starts calm communication from behind cover while another clears bystanders and positions less-lethal with lethal cover. Adrian lowers the knife briefly, then suddenly runs toward the officers as firefighters arrive with a rescue ladder.',
    ['20'],
    [
      question(
        'tmas3-practice-11-q1',
        '20',
        tts(['20.2A', '20.2D', '20.2E'], 'deescalation using time, distance, cover, and communication'),
        'Before Adrian runs, which response best reflects LD 20 deescalation principles?',
        [
          'Use cover, distance, calm communication, scene control, and coordinated resources while continuously reassessing the threat.',
          'Rush Adrian immediately because a knife is present.',
          'Stop communicating so officers do not influence his behavior.',
          'Allow the crowd to stay because bystanders can help talk him down.',
        ],
        0,
        'Deescalation is tactical, not passive. The best answer uses time, distance, cover, communication, and scene management when feasible.',
      ),
      question(
        'tmas3-practice-11-q2',
        '20',
        tts(['20.1A', '20.1B', '20.3C', '20.4C'], 'objective reasonableness and changing force options'),
        'When Adrian suddenly rushes officers with the knife, what must the force decision be based on?',
        [
          'The objectively reasonable assessment of the immediate threat, available options, distance, cover, and rapidly changing facts.',
          'The original suicidal-call label only, because the event started as a crisis call.',
          'A fixed rule that less-lethal must always be used first.',
          'Whether the crowd wants officers to end the incident quickly.',
        ],
        0,
        'LD 20 tests changing circumstances. A crisis call can become an immediate deadly-threat event, and force must be judged under the totality at that moment.',
      ),
      question(
        'tmas3-practice-11-q3',
        '20',
        tts(['20.4A', '20.4B', '20.4C'], 'deadly force and imminent threat analysis'),
        'Which fact most directly supports deadly-force consideration if Adrian closes distance with the knife?',
        [
          'He is rapidly advancing with a knife toward officers at close enough range to create an imminent threat of death or serious bodily injury.',
          'He was upset when officers first arrived.',
          'Firefighters arrived with a rescue ladder.',
          'The crowd was recording the event from below.',
        ],
        0,
        'Deadly-force analysis requires an imminent threat, not just emotional distress or public pressure.',
      ),
      question(
        'tmas3-practice-11-q4',
        '20',
        tts(['20.5A', '20.7C', '20.7D', '20.7E'], 'post-force duties, reporting, and intervention principles'),
        'After force is used and the scene is safe, what remains required?',
        [
          'Provide or summon medical aid, secure evidence, notify supervisors as required, document force facts, and address any duty-to-intervene/reporting issues.',
          'Leave immediately because the threat has stopped.',
          'Delay medical aid until every witness statement is completed.',
          'Document only the final force option and omit earlier deescalation attempts.',
        ],
        0,
        'LD 20 does not end at the trigger pull or force application. Medical aid, supervision, evidence, reporting, and intervention duties remain testable.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-12',
    'Apartment Court Order',
    'Officers respond to a 911 hang-up at an apartment. Mia has redness on her neck and says her ex-partner Carlos shoved her against a wall after seeing a text from a coworker. Carlos has a scratched forearm and says Mia “started it.” A valid protective order prohibits Carlos from contacting Mia and being at the apartment. A neighbor heard Carlos threaten, “I’ll come back after they leave.” Two children are in the bedroom crying.',
    ['25'],
    [
      question(
        'tmas3-practice-12-q1',
        '25',
        tts(['25.1A', '25.1B', '25.1C'], 'domestic-violence crime identification and dominant aggressor analysis'),
        'Which analysis best fits the conflicting injury claims?',
        [
          'Evaluate domestic-violence elements, injuries, threats, history, defensive wounds, and dominant aggressor indicators instead of assuming mutual combat.',
          'Arrest both parties automatically because both have visible marks.',
          'Ignore the neck redness because Carlos also has a scratch.',
          'Treat it as civil unless Mia requests prosecution.',
        ],
        0,
        'LD 25 tests dominant-aggressor thinking and domestic-violence classification from context, not simple injury counting.',
      ),
      question(
        'tmas3-practice-12-q2',
        '25',
        tts(['25.3A', '25.3B', '25.3C', '25.3D', '25.3E'], 'DV response, arrest decisions, victim safety, and children present'),
        'Which immediate response best protects the victim and children while preserving the case?',
        [
          'Separate parties, assess injuries and lethality factors, confirm the order, address child safety, gather statements, and make a lawful arrest decision.',
          'Mediate an apology and leave once both parties calm down.',
          'Tell Carlos to wait outside for ten minutes and return after officers clear.',
          'Ask Mia to decide whether Carlos should be arrested.',
        ],
        0,
        'DV calls require safety planning, evidence, order verification, child considerations, and lawful enforcement rather than informal mediation.',
      ),
      question(
        'tmas3-practice-12-q3',
        '25',
        tts(['25.4A', '25.4B', '25.4C', '25.4D'], 'protective orders and enforcement'),
        'What is the strongest significance of the protective order?',
        [
          'It creates a separate court-order enforcement issue and affects safety planning and arrest analysis.',
          'It matters only if Carlos physically injures Mia in front of officers.',
          'It is irrelevant because Mia opened the apartment door.',
          'It can be ignored if Carlos says he came over to talk.',
        ],
        0,
        'Protective orders are independent legal facts. Victim cooperation or suspect motive does not automatically erase order restrictions.',
      ),
      question(
        'tmas3-practice-12-q4',
        '25',
        tts(['25.5A', '25.5B'], 'DV report documentation and evidence'),
        'Which documentation best supports prosecution and safety follow-up?',
        [
          'Injuries, photos, excited statements, order terms, threat quote, child presence, neighbor observations, history, and dominant-aggressor reasoning.',
          'Only Carlos’s denial and Mia’s request about whether she wants charges.',
          'Only a checkbox saying “verbal dispute.”',
          'Only the protective-order number without the surrounding facts.',
        ],
        0,
        'DV reports need enough detail for filing, risk assessment, court orders, and later testimony.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-13',
    'School Lab Spill',
    'A school resource officer hears an explosion in a science building. Students are coughing, a teacher is missing, and a yellow vapor cloud is moving down a hallway. A custodian says two unlabeled containers were mixed near a drain. The first patrol officer begins directing students out the windward side, keeps staff from reentering, and requests fire, hazmat, EMS, and a supervisor. A parent demands to go inside to find her child.',
    ['26'],
    [
      question(
        'tmas3-practice-13-q1',
        '26',
        tts(['26.1A', '26.1B', '26.1C'], 'emergency management and initial scene priorities'),
        'What initial priority best fits LD 26 emergency-management principles?',
        [
          'Life safety, isolation, notification, and establishing command/control while avoiding unnecessary exposure.',
          'Finding the exact chemical before evacuating anyone.',
          'Letting parents enter because they know the campus layout.',
          'Keeping students nearby until every name is checked off a roster.',
        ],
        0,
        'Critical-incident questions test life safety and control first. Identification matters, but not at the expense of exposure and scene control.',
      ),
      question(
        'tmas3-practice-13-q2',
        '26',
        tts(['26.2A', '26.2B', '26.2C', '26.2D'], 'officer roles and responsibilities at critical incidents'),
        'Which officer action best reflects the patrol role before specialized resources arrive?',
        [
          'Set an initial perimeter, direct evacuation away from danger, relay observations, and prevent reentry without becoming a hazmat technician.',
          'Enter the vapor cloud to search every room alone.',
          'Collect chemical samples so hazmat knows what spilled.',
          'Allow school staff to manage the incident until fire arrives.',
        ],
        0,
        'Patrol officers stabilize and communicate. They do not self-deploy into unknown hazards or surrender command responsibilities.',
      ),
      question(
        'tmas3-practice-13-q3',
        '26',
        tts(['26.4A', '26.4B', '26.4C', '26.4D', '26.4E', '26.5A', '26.5B'], 'hazardous-materials recognition and identification clues'),
        'Which facts are most important for hazmat recognition and notification?',
        [
          'Vapor cloud color/direction, symptoms, container descriptions, location, wind direction, and what was mixed if known safely.',
          'The parent’s belief that her child is still inside.',
          'The custodian’s job title and how long he has worked there.',
          'Whether the science building usually locks at night.',
        ],
        0,
        'LD 26 tests recognition clues that can be relayed safely. Officers should not touch unknown containers to improve the description.',
      ),
      question(
        'tmas3-practice-13-q4',
        '26',
        tts(['26.6A', '26.6B', '26.6C', '26.6D', '26.6E'], 'safety, isolation, and notification at hazmat incidents'),
        'How should officers handle the parent demanding entry?',
        [
          'Keep her out of the hazard area, explain the safety reason, gather child information, and route it through command/rescue resources.',
          'Let her enter if she signs a release.',
          'Tell her to wait in the hallway nearest the spill.',
          'Allow only one parent inside at a time to limit exposure.',
        ],
        0,
        'Scene control includes emotionally hard decisions. Allowing civilians into a hot zone creates more victims and undermines command.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-14',
    'Red-Light Collision',
    'At 2315 hours, Officer Chen sees a sedan run a red light at high speed and collide with a parked truck. The driver has red watery eyes, slurred speech, and an open beer can near the center console. He says he drank “two hours ago” and refuses field sobriety tests. The sedan blocks a traffic lane, the registration expired eight months earlier, and a passenger complains of neck pain.',
    ['28'],
    [
      question(
        'tmas3-practice-14-q1',
        '28',
        tts(['28.1A', '28.1B', '28.2A', '28.2B'], 'traffic enforcement authority and lawful orders'),
        'Which facts best support the traffic stop and initial enforcement contact?',
        [
          'The officer observed the red-light violation, collision, blocked lane, and registration issue.',
          'The driver admitted he drank exactly two hours earlier.',
          'The passenger complained of pain after the collision.',
          'The parked truck owner is likely upset about the damage.',
        ],
        0,
        'LD 28 begins with observed Vehicle Code violations and officer authority. DUI and collision issues add layers but do not replace the traffic basis.',
      ),
      question(
        'tmas3-practice-14-q2',
        '28',
        tts(['28.3A', '28.3B', '28.3C', '28.3D', '28.3E'], 'common Vehicle Code violations and collision facts'),
        'Which documentation best supports the red-light collision investigation?',
        [
          'Signal phase, driver actions, witness statements, vehicle positions, roadway conditions, injury complaints, and observed violations.',
          'Only the driver’s drinking statement.',
          'Only the expired registration date.',
          'Only the parked truck’s repair estimate.',
        ],
        0,
        'Traffic questions test complete collision and violation documentation, not a single fact.',
      ),
      question(
        'tmas3-practice-14-q3',
        '28',
        tts(['28.5A', '28.5B', '28.5C', '28.5D', '28.5E', '28.5F', '28.5G', '28.5H', '28.5I'], 'DUI detection, investigation, and arrest/reporting issues'),
        'Which fact set most strongly supports continuing a DUI investigation?',
        [
          'Collision driving pattern, alcohol container, red watery eyes, slurred speech, admission to drinking, and refusal of field tests.',
          'Expired registration alone.',
          'The passenger’s neck pain alone.',
          'The fact that the crash happened at night alone.',
        ],
        0,
        'DUI analysis is totality-based. Driving, physical signs, alcohol evidence, statements, and test refusal all matter.',
      ),
      question(
        'tmas3-practice-14-q4',
        '28',
        tts(['28.2C', '28.2D'], 'vehicle removal and roadway safety considerations'),
        'What is the best vehicle-removal consideration?',
        [
          'Whether lawful authority exists to remove or store the sedan because it blocks a lane, is damaged, or cannot be safely driven.',
          'Tow the sedan only if the parked truck owner requests it.',
          'Leave the sedan in the lane until the driver sobers up.',
          'Tow every expired-registration vehicle even if it is legally parked and safe.',
        ],
        0,
        'Vehicle removal turns on lawful authority and safety, not convenience or automatic punishment.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-15',
    'Deaf Driver Crisis',
    'Officers stop a car after a minor collision. The driver, Mr. Bell, does not respond to verbal commands, keeps looking at his phone, and becomes visibly anxious as officers repeat louder commands. His passenger says Mr. Bell is Deaf and uses a text-to-speech app. Mr. Bell also has a card explaining he has autism and may avoid eye contact. A witness claims he “must be drunk” because he seemed confused after the crash.',
    ['37'],
    [
      question(
        'tmas3-practice-15-q1',
        '37',
        tts(['37.1A', '37.1B'], 'disability law and officer responsibilities'),
        'What should officers do first to keep the contact lawful and effective?',
        [
          'Recognize possible disability-related communication needs and adjust communication before treating nonresponse as defiance.',
          'Assume noncompliance because commands were loud enough.',
          'Order the passenger not to explain anything because it may bias the investigation.',
          'Arrest Mr. Bell for delay unless he immediately speaks aloud.',
        ],
        0,
        'LD 37 tests recognition and accommodation. Nonresponse can be disability-related, and officers should not escalate based on misunderstanding.',
      ),
      question(
        'tmas3-practice-15-q2',
        '37',
        tts(['37.3A', '37.3B', '37.3C', '37.3D', '37.3E', '37.3F', '37.3G'], 'physical disabilities and communication adaptations'),
        'Which communication method is most appropriate if safe at the scene?',
        [
          'Use writing, text, visual cues, or qualified communication assistance while keeping officer-safety positioning.',
          'Keep repeating commands louder until Mr. Bell complies.',
          'Rely only on the witness’s interpretation that he seemed drunk.',
          'Avoid communicating until a supervisor arrives.',
        ],
        0,
        'Communication adaptation does not eliminate officer safety; it improves accuracy while maintaining control.',
      ),
      question(
        'tmas3-practice-15-q3',
        '37',
        tts(['37.4A', '37.4B', '37.4C', '37.4D', '37.4E', '37.4F', '37.4G'], 'mental illness and behavioral-health considerations'),
        'How should officers treat anxiety, lack of eye contact, and confusion after the crash?',
        [
          'As facts requiring assessment, not automatic proof of intoxication or criminal intent.',
          'As conclusive evidence of DUI.',
          'As proof he is refusing to cooperate.',
          'As irrelevant because only physical injuries matter after a collision.',
        ],
        0,
        'LD 37 pushes officers to avoid misreading disability or crisis behaviors as guilt without more facts.',
      ),
      question(
        'tmas3-practice-15-q4',
        '37',
        tts(['37.5A', '37.5B', '37.5C', '37.5D', '37.5E'], 'Welfare and Institutions Code awareness and protective options'),
        'If Mr. Bell later expresses intent to harm himself because he is overwhelmed, what should officers evaluate?',
        [
          'Whether criteria for a mental-health hold or other protective intervention are met, while documenting behavior and statements.',
          'Whether the original traffic violation disappears.',
          'Whether the passenger can decide all legal outcomes for him.',
          'Whether officers can ignore the statement because it happened after the crash.',
        ],
        0,
        'Protective mental-health authority is separate from the traffic investigation and must be based on articulable criteria.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-16',
    'Witness Hallway Threat',
    'During a preliminary hearing break, officers assigned to courthouse security see Ray walk up to a witness in the hallway and whisper, “If you testify, your brother gets hurt next.” When an officer steps between them, Ray pulls away and shoves the officer’s arm while trying to leave. At booking, Ray gives his cousin’s name and date of birth. Later he tells another detainee he called in a fake bomb threat last month to delay the same case.',
    ['39'],
    [
      question(
        'tmas3-practice-16-q1',
        '39',
        tts(['39.1A', '39.1B'], 'witness intimidation and crimes against justice'),
        'Which charge theory is most directly supported by Ray’s hallway statement?',
        [
          'Witness intimidation or threat-related interference with the justice process.',
          'Trespass, because the statement happened in a hallway.',
          'Civil harassment only, because the witness was not physically touched.',
          'Vandalism, because the statement disrupted court operations.',
        ],
        0,
        'LD 39 focuses on crimes against the justice system. Threatening a witness because of testimony is more than a generic disturbance.',
      ),
      question(
        'tmas3-practice-16-q2',
        '39',
        tts(['39.2A', '39.2B'], 'resisting, delaying, or obstructing officers'),
        'Which fact most directly supports a resisting or obstructing analysis?',
        [
          'Ray shoved the officer’s arm while the officer intervened in the courthouse hallway threat.',
          'Ray whispered instead of speaking loudly.',
          'The witness looked scared after Ray walked away.',
          'The hearing was already in recess.',
        ],
        0,
        'Physical interference with an officer performing lawful duties is the tested obstruction fact.',
      ),
      question(
        'tmas3-practice-16-q3',
        '39',
        tts(['39.3A', '39.3B'], 'false identification and false emergency reports'),
        'Ray giving his cousin’s identifying information raises what additional issue?',
        [
          'False identification or false information to officers during a lawful detention or arrest process.',
          'Accessory after the fact for the cousin.',
          'No issue because booking records can be corrected later.',
          'Only a civil identity-theft claim by the cousin.',
        ],
        0,
        'LD 39 includes false information to officers. The fact that officers can later discover the truth does not make the conduct irrelevant.',
      ),
      question(
        'tmas3-practice-16-q4',
        '39',
        tts(['39.3A', '39.4A', '39.4B'], 'false emergency reports and justice-system disruption'),
        'What is the best way to handle Ray’s fake-bomb-threat admission?',
        [
          'Document it as a potential false emergency report or justice-system disruption and investigate corroboration before filing.',
          'Ignore it because it was made to another detainee.',
          'File it automatically without checking whether the threat occurred.',
          'Treat it only as courthouse gossip because the case is unrelated to today’s arrest.',
        ],
        0,
        'The statement may be significant, but officers still need corroboration and accurate documentation.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-17',
    'Loaded Console Gun',
    'Officers stop a vehicle for a cracked windshield. The driver, Ken, appears nervous and says he is on probation but is “not sure” of the search terms. A passenger leans forward toward the center console. Officers see a pistol grip protruding from the partly open console. The pistol is loaded, has no serial number visible, and a short-barreled rifle is later found in the trunk. Ken has a prior felony conviction.',
    ['40'],
    [
      question(
        'tmas3-practice-17-q1',
        '40',
        tts(['40.2A', '40.2B', '40.3A', '40.3D'], 'loaded and concealed firearm possession issues'),
        'Which weapons issue is most directly raised by the pistol in the center console?',
        [
          'Concealed and loaded firearm possession in a vehicle, depending on access, knowledge, and statutory elements.',
          'No issue because the console was partly open.',
          'Only a traffic equipment violation.',
          'A civil registration problem only.',
        ],
        0,
        'LD 40 requires officers to identify loaded/concealed firearm issues from facts like location, access, and firearm condition.',
      ),
      question(
        'tmas3-practice-17-q2',
        '40',
        tts(['40.1A', '40.1B', '40.4A', '40.4B'], 'prohibited weapons and restricted persons'),
        'Why does Ken’s prior felony matter?',
        [
          'It may make him a restricted person prohibited from possessing firearms or ammunition.',
          'It automatically proves the passenger had no access to the weapon.',
          'It allows officers to ignore search-and-seizure limits.',
          'It matters only if the gun was fired during the stop.',
        ],
        0,
        'Restricted-person status is a separate weapons analysis. It does not replace proof of possession or lawful search authority.',
      ),
      question(
        'tmas3-practice-17-q3',
        '40',
        tts(['40.1A', '40.1B'], 'prohibited weapon recognition'),
        'The short-barreled rifle most directly requires officers to evaluate what issue?',
        [
          'Whether it is a prohibited weapon under the applicable weapons statutes.',
          'Whether the windshield crack caused the weapon to be unsafe.',
          'Whether the trunk was locked before the stop.',
          'Whether the passenger owns a hunting license.',
        ],
        0,
        'LD 40 includes recognizing prohibited weapons, not just handguns in passenger compartments.',
      ),
      question(
        'tmas3-practice-17-q4',
        '40',
        tts(['40.5A', '40.5C'], 'unlawful use and weapons documentation'),
        'Which documentation best supports later review of the weapons charges?',
        [
          'Exact firearm locations, loaded status, serial-number condition, who had access, statements, probation information, and safe handling steps.',
          'Only that officers “found guns” during the traffic stop.',
          'Only Ken’s nervous behavior.',
          'Only the cracked windshield because it justified the stop.',
        ],
        0,
        'Weapons cases are fact-specific. Possession, access, condition, serial number, and safety handling all matter.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-18',
    'Transit Center Package',
    'A transit officer receives a report of a man photographing security cameras, emergency exits, and electrical panels at a regional rail station. The man leaves a backpack near a support column and walks away while speaking on a phone in a foreign language. A maintenance worker says the same man asked earlier about “when the station is most crowded.” The backpack has wires visible through a torn seam, but no one has heard an explosion or threat.',
    ['43'],
    [
      question(
        'tmas3-practice-18-q1',
        '43',
        tts(['43.1A', '43.1B', '43.1C', '43.1D', '43.1E'], 'terrorism indicators without profiling'),
        'Which facts are legitimate terrorism-awareness indicators without relying on protected status?',
        [
          'Surveillance of security features, questions about crowd timing, leaving a suspicious backpack, and visible wires.',
          'Speaking in a foreign language on the phone.',
          'Being present at a transit station during commute hours.',
          'Taking photographs in public by itself.',
        ],
        0,
        'LD 43 emphasizes behavior and threat indicators, not ethnicity, language, religion, or protected characteristics.',
      ),
      question(
        'tmas3-practice-18-q2',
        '43',
        tts(['43.2A', '43.2B', '43.2C', '43.2D'], 'prevention and deterrence response'),
        'Which first response best fits prevention and deterrence principles?',
        [
          'Isolate the package area, avoid touching it, move people away, notify appropriate resources, and preserve observations about the subject.',
          'Open the backpack quickly to determine whether the station can stay open.',
          'Ignore the package because no threat was called in.',
          'Detain every person speaking a language officers do not understand.',
        ],
        0,
        'The safe response is behavior-based and protective. Officers do not need an explosion or explicit threat before isolating a suspicious package.',
      ),
      question(
        'tmas3-practice-18-q3',
        '43',
        tts(['43.3A', '43.3B'], 'critical infrastructure protection'),
        'Why does the transit-station location matter?',
        [
          'Rail stations can be critical infrastructure, so disruptions, surveillance, and suspicious packages may have broader public-safety consequences.',
          'Transit stations are private property where all photography is automatically illegal.',
          'Critical-infrastructure rules mean officers can skip documentation.',
          'The location matters only if federal officers are already on scene.',
        ],
        0,
        'LD 43 tests recognition of critical infrastructure and consequences, not automatic criminalization of public activity.',
      ),
      question(
        'tmas3-practice-18-q4',
        '43',
        tts(['43.4A', '43.4B', '43.4C'], 'intelligence cycle and suspicious-activity reporting'),
        'Which information should officers preserve for intelligence or suspicious-activity reporting channels?',
        [
          'Behavioral observations, timeline, subject description, photos taken, questions asked, package location, witnesses, and notification chain.',
          'Only the subject’s language because it is the easiest detail to remember.',
          'Only whether the package contained an actual explosive after disposal.',
          'Only the maintenance worker’s opinion that the man looked suspicious.',
        ],
        0,
        'Suspicious-activity reporting depends on objective behavior, timeline, and critical facts that can be evaluated later.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-19',
    'Search Warrant Knock',
    'A team serves a residential search warrant for robbery evidence. As officers knock and announce, a person inside yells, “Flush the phones,” and another runs toward a back bedroom. Officers enter, detain three occupants, and see a handgun on a couch cushion next to a robbery victim’s wallet. One occupant is handcuffed in the hallway and asks, “Am I under arrest?” A second officer starts asking where the stolen phones are before Miranda warnings are given.',
    ['15', '16', '20'],
    [
      question(
        'tmas3-practice-19-q1',
        '16',
        tts(['16.2A', '16.2B', '16.2D', '16.2E'], 'warrant execution scope and evidence nexus'),
        'Which search principle best controls the residential warrant execution?',
        [
          'Officers must stay within the warrant’s authorized places/items and any recognized exception supported by the developing facts.',
          'A robbery warrant automatically authorizes every digital and container search forever.',
          'The shout about flushing phones cancels the need to follow the warrant.',
          'Any person inside can consent to search all rooms after entry.',
        ],
        0,
        'LD 16 warrant questions test scope and nexus. Exigency or plain view may add authority, but officers still articulate the lane they are using.',
      ),
      question(
        'tmas3-practice-19-q2',
        '16',
        tts(['16.3A', '16.3B'], 'plain view during lawful warrant entry'),
        'What is the strongest plain-view analysis for the handgun and wallet?',
        [
          'If officers are lawfully in the room and the wallet’s link to the robbery and the gun’s evidentiary or safety significance are immediately apparent, seizure may be justified.',
          'Plain view allows officers to search every phone in the room without more.',
          'Plain view never applies during a warrant service.',
          'The gun must be ignored unless someone admits ownership first.',
        ],
        0,
        'Plain view can apply during lawful presence, but it does not expand into unlimited searches.',
      ),
      question(
        'tmas3-practice-19-q3',
        '15',
        tts(['15.5B', '15.5C', '15.5F'], 'Miranda during custodial interrogation at a warrant scene'),
        'What issue is raised when the handcuffed occupant is asked where the stolen phones are?',
        [
          'Whether the occupant is in custody and the question is interrogation requiring Miranda before an incriminating response.',
          'No issue because warrants erase Miranda requirements.',
          'Only officer-safety questioning because stolen phones are never testimonial.',
          'A consensual encounter because the occupant asked if he was under arrest.',
        ],
        0,
        'A warrant scene can still create custody. Direct questions about stolen property are likely interrogation unless an exception applies.',
      ),
      question(
        'tmas3-practice-19-q4',
        '20',
        tts(['20.1A', '20.1B', '20.3C', '20.5A'], 'force reasonableness and post-force/reporting duties during tactical entries'),
        'If force is used to stop the person running toward the bedroom, what must officers be able to explain?',
        [
          'Why the force was objectively reasonable based on the threat, resistance, warrant context, safety facts, and available alternatives at that moment.',
          'That any force is automatically reasonable during every search warrant.',
          'That the person ran, so officers do not need to describe the force used.',
          'That the warrant target was robbery, so post-force medical and reporting duties do not apply.',
        ],
        0,
        'LD 20 remains active during warrant service. Officers must articulate the force decision and complete post-force responsibilities.',
      ),
    ],
  ),
  scenario(
    'tmas3-practice-20',
    'Shelter Evacuation',
    'A winter storm damages a community shelter where officers are helping with evacuation. Inside, Tara says her partner Sam violated a domestic-violence order and followed her to the shelter. Sam is agitated, pacing, and yelling that Tara “will pay” if she leaves with officers. A volunteer says Sam may have an intellectual disability and becomes overwhelmed by loud commands. At the same time, a generator outside starts smoking near stacked fuel cans.',
    ['25', '26', '37'],
    [
      question(
        'tmas3-practice-20-q1',
        '25',
        tts(['25.3A', '25.3B', '25.3C', '25.4A', '25.4B'], 'DV response and protective-order enforcement during a larger incident'),
        'Which DV response is most defensible while the shelter evacuation is underway?',
        [
          'Separate Tara and Sam, verify the order, assess threats and safety, document statements, and coordinate an arrest or protective plan without losing incident control.',
          'Delay all DV action until the storm incident is completely over.',
          'Ask Tara to leave alone so officers can focus only on evacuation.',
          'Ignore the order if Sam appears overwhelmed by the shelter noise.',
        ],
        0,
        'Critical incidents do not erase DV duties. Officers must integrate protective-order enforcement and victim safety into the larger operation.',
      ),
      question(
        'tmas3-practice-20-q2',
        '26',
        tts(['26.1A', '26.2A', '26.3A', '26.8A', '26.8B', '26.8C'], 'critical incident command and fire/explosive hazard coordination'),
        'What is the best response to the smoking generator and fuel cans?',
        [
          'Treat it as an evolving fire/explosive hazard, isolate the area, notify fire resources, and route actions through incident command.',
          'Move the fuel cans closer to the building so rain does not spread vapors.',
          'Ask shelter volunteers to keep operating the generator until evacuation is finished.',
          'Ignore it unless flames are visible.',
        ],
        0,
        'LD 26 expects officers to recognize secondary hazards and use command/notification instead of creating more victims.',
      ),
      question(
        'tmas3-practice-20-q3',
        '37',
        tts(['37.1A', '37.1B', '37.4A', '37.4B', '37.4C'], 'disability-aware communication during enforcement'),
        'How should officers account for the report that Sam may have an intellectual disability?',
        [
          'Use clear, calm, simple communication and time/distance when feasible while still addressing threats, order violations, and safety.',
          'Stop all enforcement because disability prevents criminal responsibility in the field.',
          'Use louder commands because disability means Sam did not understand the first command.',
          'Rely on Tara to control Sam because she knows him best.',
        ],
        0,
        'Disability-aware communication improves safety but does not require officers to ignore threats or lawful enforcement duties.',
      ),
      question(
        'tmas3-practice-20-q4',
        '25',
        tts(['25.5A', '25.5B', '37.5A'], 'documentation when DV, disability, and protective intervention overlap'),
        'Which documentation best captures the mixed issues in this scenario?',
        [
          'Order terms, threats, separation and safety steps, disability-related communication adjustments, evacuation hazards, and command notifications.',
          'Only the generator hazard because it affected more people.',
          'Only Tara’s statement because Sam may have a disability.',
          'Only Sam’s behavior after officers gave commands.',
        ],
        0,
        'The strongest report separates the DV, disability, and critical-incident facts so each legal and safety decision is reviewable.',
      ),
    ],
  ),
]

export const tmas3Scenarios = appendTrueFalseFollowUps(
  polishPracticeScenarios([...rawTmas3Scenarios, ...tmas3ExpansionScenarios]),
)
